//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonDBEntities : DbContext
    {
        public SalonDBEntities()
            : base("name=SalonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_KomadniNamestaj> tbl_KomadniNamestaj { get; set; }
        public virtual DbSet<tbl_Namestaj> tbl_Namestaj { get; set; }
        public virtual DbSet<tbl_Racun> tbl_Racun { get; set; }
        public virtual DbSet<tbl_Stavke> tbl_Stavke { get; set; }
        public virtual DbSet<tbl_StavkeNaRacunu> tbl_StavkeNaRacunu { get; set; }
        public virtual DbSet<tblKorisnici> tblKorisnicis { get; set; }
        public virtual DbSet<tblSalon> tblSalons { get; set; }
        public virtual DbSet<tblUloge> tblUloges { get; set; }
    }
}
