//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StavkeNaRacunu
    {
        public int Id { get; set; }
        public int RacunId { get; set; }
        public int StavkeId { get; set; }
    
        public virtual tbl_Racun tbl_Racun { get; set; }
        public virtual tbl_Stavke tbl_Stavke { get; set; }
    }
}
