//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Racun
    {
        public tbl_Racun()
        {
            this.tbl_StavkeNaRacunu = new HashSet<tbl_StavkeNaRacunu>();
        }
    
        public int Id { get; set; }
        public int Porez { get; set; }
        public decimal CenaSaPorezom { get; set; }
        public System.DateTime DatumKupovine { get; set; }
        public string Kupac { get; set; }
    
        public virtual ICollection<tbl_StavkeNaRacunu> tbl_StavkeNaRacunu { get; set; }
    }
}
