//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class tbl_Namestaj
    {
        public tbl_Namestaj()
        {
            this.tbl_KomadniNamestaj = new HashSet<tbl_KomadniNamestaj>();
        }
    
        public int Id { get; set; }

        [Remote("IsUnique", "NamestajController", ErrorMessage = " Ime je zauzeto.")]
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<tbl_KomadniNamestaj> tbl_KomadniNamestaj { get; set; }
    }
}
