//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stavke
    {
        public tbl_Stavke()
        {
            this.tbl_StavkeNaRacunu = new HashSet<tbl_StavkeNaRacunu>();
        }
    
        public int Id { get; set; }
        public string KomadNamestaja { get; set; }
        public decimal KomCena { get; set; }
        public int Kolicina { get; set; }
        public string NazivSalona { get; set; }
    
        public virtual ICollection<tbl_StavkeNaRacunu> tbl_StavkeNaRacunu { get; set; }
    }
}
