//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KomadniNamestaj
    {
        public int Id { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string ZemljaProizvodnje { get; set; }
        public Nullable<System.DateTime> GodinaProizvodnja { get; set; }
        public decimal JedinicnaCena { get; set; }
        public int StanjeKolicina { get; set; }
        public int SalonId { get; set; }
        public int KategorijaId { get; set; }
        public string Slika { get; set; }
    
        public virtual tbl_Namestaj tbl_Namestaj { get; set; }
        public virtual tblSalon tblSalon { get; set; }
    }
}
