//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_namestaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalon
    {
        public int Id { get; set; }
     
        public string Nazic { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string WebStranica { get; set; }
        public string Pib { get; set; }
        public string BrojZiroRacuna { get; set; }
    }
}
